version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gothstarter-postgresdb
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  dev-service:
    container_name:  gothstarter-dev-container
    build:
      context: .
      dockerfile: Development.Dockerfile
      args:
        USERNAME: stephan
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ./:/app
    ports:
      - "4000:4000"

